### ISSUE TITLE
API key description is required but docs say it isn't

### ISSUE THREAD

**Issue by Sembiance** [typesense/typesense-website#116]
The website here: https://typesense.org/docs/0.22.1/api/api-keys.html#create-an-api-key
Says that `description` when creating an API key is NOT required.
If you try and create an API key without a description (via HTTP REST) I get the error message: `Could not find a description key.`

Either docs are incorrect, or the API is incorrectly requiring this property.

**Comment by kishorenc** [comment]
The docs are incorrect, I will update the docs.

**Comment by kishorenc** [comment]
Fixed, will be deployed in the next update.
