### ISSUE TITLE
Info about meiliserarch maybe incorrect

### ISSUE THREAD

**Issue by manasomali** [typesense/typesense-website#134]
## Description

In the overview page, limits section, for Meilisearch the "Number of API Keys" is "2". Maybe this is incorrect.

There are the possibility of create new keys:
https://docs.meilisearch.com/learn/security/master_api_keys.html#creating-an-api-key

### Sugestion

Change "2" to "2 default, can be modified"

**Comment by jasonbosco** [comment]
Thanks @manasomali!
