### ISSUE TITLE
404 Error - Scoped Search API Keys

### ISSUE THREAD

**Issue by fishcharlie** [typesense/typesense-website#139]
## Description

On the [Multi Tenant Applications section of Organizing Collections page](https://typesense.org/docs/guide/organizing-collections.html#multi-tenant-applications) it has a link to [Scoped Search API Keys](https://typesense.org/docs/0.23.1/api/keys.html#generate-scoped-search-key). However, this page returns a 404 result.

According to the create API keys documentation, I don't see any arguments it accepts for a Scoped Search API Key: https://typesense.org/docs/0.23.1/api/api-keys.html#create-an-api-key.

What is the recommended way to have a Multi Tenant Application?

## Steps to reproduce

See above

## Expected Behavior

1. It to show documentation about how to create a Scoped Search API Key

## Actual Behavior

1. 404 page

## Metadata

NA

**Comment by jasonbosco** [comment]
This is what the link should point to: https://typesense.org/docs/0.23.1/api/api-keys.html#generate-scoped-search-key

Will fix that shortly. Thank you for catching it.

**Comment by jasonbosco** [comment]
Fixed in 515373026f3bd3c9f34eb4e9c0c56a76b1054699
