### ISSUE TITLE
Homepage `undefined` issue when search is emptied

### ISSUE THREAD

**Issue by imjared** [typesense/typesense-website#16]
## Description

See title

## Steps to reproduce

On project homepage, clear all text from the Harry Potter demo search box.

## Expected Behavior

I'd expect to see either no results (for no search text) or have this line removed

## Actual Behavior

It gives a result of `undefined result. Page 1 of NaN.`

<img src="https://user-images.githubusercontent.com/525011/73381747-4812b500-4294-11ea-8770-92d3d641e332.png" width="50%" />

## Metadata

**Typsense Version**: not sure.

**OS**: latest Mac OS, latest Chrome stable.

**Comment by kishorenc** [comment]
Thank you, this has been fixed.
