### ISSUE TITLE
Description of configuring via environment variables is missing the "TYPESENSE_" prefix

### ISSUE THREAD

**Issue by JaredReisinger** [typesense/typesense-website#17]
I just tried spinning up a typesense Docker image (0.11.1), and despite defining `DATA_DIR` and `API_KEY`, I was getting the error "Invalid configuration: Data directory is not specified."

Looking at the `load_config_env()` source code (https://github.com/typesense/typesense/blob/eb0707a68bfad16c60a38e1e927cd8a92b47984e/include/config.h#L146-L168), it appears that the environment variables are all prefixed with `TYPESENSE_`.  So, where the guide reads:

> ### Using environment variables
> 
> If you wish to use environment variables, you can do that too. The environment variables map to the command line arguments documented above: just use CAPS and underscores instead of hyphens. For example, use `DATA_DIR` for the `--data-dir` argument.

... it should probably say something like:

> ### Using environment variables
> 
> If you wish to use environment variables, you can do that too. The environment variables map to the command line arguments documented above: just use CAPS and underscores instead of hyphens, and prefix the name with `TYPESENSE_`. For example, use `TYPESENSE_DATA_DIR` for the `--data-dir` argument.

**Comment by kishorenc** [comment]
Thanks. Fixed, will be available in next release.
