### ISSUE TITLE
Endorse Minibar search bar

### ISSUE THREAD

**Issue by CodeSandwich** [typesense/typesense-website#183]
## Description

[Minibar](https://github.com/jquery/typesense-minibar) is a great search bar component for TypeSense. It's light weight, written in pure JS with no dependencies, simple and easy to customize. For many users it may be a great alternative to the rather heavy and complicated Algolia's UI components. Minibar is fully FOSS, it's licensed under MIT and developed by JQuery people.

Maybe you could officially endorse Minibar? You could add a reference to it in your documentation and maybe a minimal code example.

**Comment by jasonbosco** [comment]
Yeah agreed, happy to add it. 

Do you want to add to [this page](https://typesense.org/docs/guide/search-ui-components.html) and do a PR?

**Comment by jasonbosco** [comment]
CC: @Krinkle - thank you for building Minibar!

**Comment by jasonbosco** [comment]
I've added a link to our docs.
