### ISSUE TITLE
Interaction between Hybrid Search and URL params query_by, prefix, num_typos, sort_by, etc

### ISSUE THREAD

**Issue by themerk** [typesense/typesense-website#199]
The docs don't make it clear how Hybrid Search interacts with other query parameters. I think these special cases should be documented either against the affected URL parameters or at least mentioned in the Hybrid Search section.

As an example, here's my non-hybrid search parameters:
```js
let search_parameters = {
	q: 'chair',
	query_by: 'barcode,name,description',
	prefix: 'false,true,true',
	query_by_weights: '10,1,1',
	num_typos: '0,2,2',
	sort_by: '_text_match:desc,name:asc',
}
```

I then add `embedding` (an auto-embedding field) to the `query_by` to enable Hybrid Search:
```js
	query_by: 'embedding,barcode,name,description',
```

1. Typesense now requires an extra item in the list for `prefix`, `query_by_weights` and `num_typos` even though this isn't meaningful for embeddings. What value should be specified?
2. I'm ranking by relevance and using `name:asc` as a tie-breaker. In a hybrid search relevance comes from the rank fusion score. The docs show how to use the _vector distance_ as a tie-breaker, but not how to include the _rank fusion score_ in a list of sort fields.

**Comment by kishorenc** [comment]
Thanks for the feedback.

> Typesense now requires an extra item in the list for prefix, query_by_weights and num_typos even though this isn't meaningful for embeddings. What value should be specified?

We should think about how to make these parameters account for the embedding field, which does not require those parameters. 

> I'm ranking by relevance and using name:asc as a tie-breaker. In a hybrid search relevance comes from the rank fusion score. The docs show how to use the vector distance as a tie-breaker, but not how to include the rank fusion score in a list of sort fields.

During hybrid search, `_text_match` clause in sort by already refers to the fusion score.

**Comment by themerk** [comment]
> We should think about how to make these parameters account for the embedding field, which does not require those parameters.

I'm not sure what the most intuitive way would be. I guess it doesn't matter as long as it is documented well - I pretty much followed the Semantic/Hybrid Search sections step-by-step to implement it. Typesense also gave me clear, meaningful HTTP 400 errors when the parameter lists were shorter than the `query_by` list.

One consideration is that if you ever want to make the 30/70% weightings for the Rank Fusion Score adjustable (and I'm not suggesting that is needed at all, but someone might ask in future), the logical way would be using the `query_by_weights` to set a weighting for the embeddings field. So maybe `query_by_weights` should require a value of `0` for any embeddings now (meaning 'default rank fusion weightings') to allow for forward compatibility.

> During hybrid search, `_text_match` clause in sort by already refers to the fusion score.

Ah ok great. This was not at all obvious from the docs so I'd just suggest a small mention under **Hybrid Sorting**.

**Comment by kishorenc** [comment]
Thank you, I've documented how `_text_match` refers to fusion score and the gotcha with parameters like `query_by_weights` that must match the length of `query_by` even if they don't apply to embedding field types.

> So maybe query_by_weights should require a value of 0 for any embeddings now (meaning 'default rank fusion weightings') to allow for forward compatibility.

We've recently introduced a feature to configure this via `vector_query` since that seemed clearer in intent.
