### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by fabien** [typesense/typesense-website#23]
https://github.com/typesense/typesense-website/blob/dbcb2b7807793abbfeb7a4369afd69f2cf8dc438/typesense.org/docs/0.13.0/api.html#L1714

Should be (missing parenthesis after aliases - possibly elsewhere in the docs, too):

```javascript
client.aliases().upsert('companies', aliased_collection)
```

**Comment by kishorenc** [comment]
Thanks, this was fixed in a recent update.
