### ISSUE TITLE
Add new cookbook for Testcontainers Typesense module

### ISSUE THREAD

**Issue by eddumelendez** [typesense/typesense-website#282]
## Description

Testcontainers for Java 1.20.4 provides a [Typesense module](https://java.testcontainers.org/modules/typesense/). It would be nice to add a new cookbok `Running Tests with Testcontainers`

I can contribute.

**Comment by jasonbosco** [comment]
Thank you for offering to contribute. A PR would be great.

**Comment by jasonbosco** [comment]
Thank you! I've merged it in.
