### ISSUE TITLE
Add how to update Typesense

### ISSUE THREAD

**Issue by Nick-Mazuk** [typesense/typesense-website#42]
In the guides section, it would be great to have a small section on how to update Typesense. I'm willing to add this to the Guides page.

I believe this is the process overview:

1. Install the new version of Typesense
2. Restart the server
3. If working in cluster mode, wait until the health status is 200 before updating the next node

If that's the right process and if this is a worthy addition, I'll go ahead and create a PR to add this.

**Comment by jasonbosco** [comment]
@Nick-Mazuk That's pretty much it! A PR would be great 🙏
