### ISSUE TITLE
Golang logo trasparency is scary

### ISSUE THREAD

**Issue by r3vit** [typesense/typesense-website#86]
## Description

In the homepage the section "API Libraries in your Favorite Languages" contains the Golang Logo with a particular transparency that makes the gopher really scary.

## Steps to reproduce

Go to the Typesense homepage.

Scroll to the "API Libraries" section.

[Screenshot](https://imgur.com/O6oI4Ym)

## Expected Behavior

A normal logo or the new "Go" logo.

## Actual Behavior

A scary gopher.

## Metadata

Edit: [Bonus Scary Tweet](https://twitter.com/bradfitz/status/1415340241003577351)

**Comment by jasonbosco** [comment]
Ha! That was an entertaining tweet thread! Just updated to the new logo.
