### ISSUE TITLE
Typo in Typo Tolerance Feature Description.

### ISSUE THREAD

**Issue by Prathamesh-Shanbhag** [typesense/typesense-website#96]
## Description

Typo in Feature Description
## Steps to reproduce

![image](https://user-images.githubusercontent.com/70568620/132404966-436e3eb0-4b5a-43b3-b621-602cb61a9c95.png)

## Actual Behavior

Correct Spellng to Spelling

**Comment by jasonbosco** [comment]
The typo is intended, to make a point about typo tolerance :)

**Comment by Prathamesh-Shanbhag** [comment]
OH, it was intentional!
Extremely sorry about that!
