### ISSUE TITLE
Typo in Feature Description

### ISSUE THREAD

**Issue by Prathamesh-Shanbhag** [typesense/typesense-website#98]
## Description

Typo in Feature: Grouping

## Steps to reproduce

![image](https://user-images.githubusercontent.com/70568620/132484190-126e6508-3a4a-4d98-ba93-73824a531925.png)

There is a Typo in "Variety" But I made a Typo Correction issue earlier as well, I am hoping this isn't intentional too?
If it is you can close this one too.
If not I'll make a PR with the correction

**Comment by jasonbosco** [comment]
This was indeed a typo, thanks @Prathamesh-Shanbhag. I've merged your PR.
